"""empty message

Revision ID: 07754f396a7d
Revises: 1f16eecaa91c
Create Date: 2022-08-29 23:08:28.224082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07754f396a7d'
down_revision = '1f16eecaa91c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'website')
    # ### end Alembic commands ###
