"""empty message

Revision ID: 7a2aead062bd
Revises: 3ed05af0206b
Create Date: 2022-08-29 19:58:23.926413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2aead062bd'
down_revision = '3ed05af0206b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('show_date', sa.DateTime(), nullable=False))
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Show', 'show_date')
    # ### end Alembic commands ###
