"""empty message

Revision ID: 9d2a447606ff
Revises: 7a2aead062bd
Create Date: 2022-08-29 21:06:32.689108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d2a447606ff'
down_revision = '7a2aead062bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_column('Show', 'show_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('show_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('Show', 'date')
    # ### end Alembic commands ###
